/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/matches`; params?: Router.UnknownInputParams; } | { pathname: `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/profile/components/MatchDetailsContainer`; params?: Router.UnknownInputParams; } | { pathname: `/profile/components/MatchDetailsHeader`; params?: Router.UnknownInputParams; } | { pathname: `/profile/components/atoms/LineGraph`; params?: Router.UnknownInputParams; } | { pathname: `/profile/components/atoms/ListCard`; params?: Router.UnknownInputParams; } | { pathname: `/profile/components/atoms/ListHeader`; params?: Router.UnknownInputParams; } | { pathname: `/profile/components/atoms/StatCard`; params?: Router.UnknownInputParams; } | { pathname: `/profile/components/atoms/TimeRangeSheet`; params?: Router.UnknownInputParams; } | { pathname: `/profile/components/molecules/DetailsCard`; params?: Router.UnknownInputParams; } | { pathname: `/profile/components/molecules/StrengthContainer`; params?: Router.UnknownInputParams; } | { pathname: `/profile/components/molecules/WeaknessContainer`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/matches`; params?: Router.UnknownOutputParams; } | { pathname: `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/profile/components/MatchDetailsContainer`; params?: Router.UnknownOutputParams; } | { pathname: `/profile/components/MatchDetailsHeader`; params?: Router.UnknownOutputParams; } | { pathname: `/profile/components/atoms/LineGraph`; params?: Router.UnknownOutputParams; } | { pathname: `/profile/components/atoms/ListCard`; params?: Router.UnknownOutputParams; } | { pathname: `/profile/components/atoms/ListHeader`; params?: Router.UnknownOutputParams; } | { pathname: `/profile/components/atoms/StatCard`; params?: Router.UnknownOutputParams; } | { pathname: `/profile/components/atoms/TimeRangeSheet`; params?: Router.UnknownOutputParams; } | { pathname: `/profile/components/molecules/DetailsCard`; params?: Router.UnknownOutputParams; } | { pathname: `/profile/components/molecules/StrengthContainer`; params?: Router.UnknownOutputParams; } | { pathname: `/profile/components/molecules/WeaknessContainer`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/matches${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `/profile/components/MatchDetailsContainer${`?${string}` | `#${string}` | ''}` | `/profile/components/MatchDetailsHeader${`?${string}` | `#${string}` | ''}` | `/profile/components/atoms/LineGraph${`?${string}` | `#${string}` | ''}` | `/profile/components/atoms/ListCard${`?${string}` | `#${string}` | ''}` | `/profile/components/atoms/ListHeader${`?${string}` | `#${string}` | ''}` | `/profile/components/atoms/StatCard${`?${string}` | `#${string}` | ''}` | `/profile/components/atoms/TimeRangeSheet${`?${string}` | `#${string}` | ''}` | `/profile/components/molecules/DetailsCard${`?${string}` | `#${string}` | ''}` | `/profile/components/molecules/StrengthContainer${`?${string}` | `#${string}` | ''}` | `/profile/components/molecules/WeaknessContainer${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/matches`; params?: Router.UnknownInputParams; } | { pathname: `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/profile/components/MatchDetailsContainer`; params?: Router.UnknownInputParams; } | { pathname: `/profile/components/MatchDetailsHeader`; params?: Router.UnknownInputParams; } | { pathname: `/profile/components/atoms/LineGraph`; params?: Router.UnknownInputParams; } | { pathname: `/profile/components/atoms/ListCard`; params?: Router.UnknownInputParams; } | { pathname: `/profile/components/atoms/ListHeader`; params?: Router.UnknownInputParams; } | { pathname: `/profile/components/atoms/StatCard`; params?: Router.UnknownInputParams; } | { pathname: `/profile/components/atoms/TimeRangeSheet`; params?: Router.UnknownInputParams; } | { pathname: `/profile/components/molecules/DetailsCard`; params?: Router.UnknownInputParams; } | { pathname: `/profile/components/molecules/StrengthContainer`; params?: Router.UnknownInputParams; } | { pathname: `/profile/components/molecules/WeaknessContainer`; params?: Router.UnknownInputParams; };
    }
  }
}
